spring.application.name=MoneyMachine
server.port=8080
server.ssl.enabled=false
springdoc.swagger-ui.url=/openapi.yaml
spring.h2.console.enabled=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
spring.config.import=file:backend/.env[.properties]