spring.application.name=MoneyMachine
server.port=8080
server.ssl.enabled=false
springdoc.swagger-ui.url=/openapi.yaml
spring.h2.console.enabled=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
spring.config.import=optional:file:backend/.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.settings.web-allow-others=true
